package com.jy.domain;

import java.util.Date;

public class Friend {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.fid
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    private Integer fId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.fname
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    private String fName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.sex
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.birthday
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.email
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.mobile
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.faddress
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    private String fAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.fdetail
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    private String fDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.fid
     *
     * @return the value of friend.fid
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    public Integer getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.fid
     *
     * @param fId the value for friend.fid
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    public void setfId(Integer fId) {
        this.fId = fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.fname
     *
     * @return the value of friend.fname
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    public String getfName() {
        return fName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.fname
     *
     * @param fName the value for friend.fname
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    public void setfName(String fName) {
        this.fName = fName;
    }



    public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.birthday
     *
     * @return the value of friend.birthday
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.birthday
     *
     * @param birthday the value for friend.birthday
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.email
     *
     * @return the value of friend.email
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.email
     *
     * @param email the value for friend.email
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.mobile
     *
     * @return the value of friend.mobile
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.mobile
     *
     * @param mobile the value for friend.mobile
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.faddress
     *
     * @return the value of friend.faddress
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    public String getfAddress() {
        return fAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.faddress
     *
     * @param fAddress the value for friend.faddress
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    public void setfAddress(String fAddress) {
        this.fAddress = fAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.fdetail
     *
     * @return the value of friend.fdetail
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    public String getfDetail() {
        return fDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.fdetail
     *
     * @param fDetail the value for friend.fdetail
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    public void setfDetail(String fDetail) {
        this.fDetail = fDetail;
    }
}