package com.jy.domain;

public class Group {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fgroup.gid
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    private Integer gId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fgroup.gname
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    private String gName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fgroup.gdetail
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    private String gDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fgroup.gid
     *
     * @return the value of fgroup.gid
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    public Integer getgId() {
        return gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fgroup.gid
     *
     * @param gId the value for fgroup.gid
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    public void setgId(Integer gId) {
        this.gId = gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fgroup.gname
     *
     * @return the value of fgroup.gname
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    public String getgName() {
        return gName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fgroup.gname
     *
     * @param gName the value for fgroup.gname
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    public void setgName(String gName) {
        this.gName = gName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fgroup.gdetail
     *
     * @return the value of fgroup.gdetail
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    public String getgDetail() {
        return gDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fgroup.gdetail
     *
     * @param gDetail the value for fgroup.gdetail
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    public void setgDetail(String gDetail) {
        this.gDetail = gDetail;
    }
}