package com.jy.dao;

import java.util.List;

import com.jy.domain.Friend;

public interface FriendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    int deleteByPrimaryKey(Integer fId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    int insert(Friend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    int insertSelective(Friend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    Friend selectByPrimaryKey(Integer fId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    int updateByPrimaryKeySelective(Friend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(Friend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    int updateByPrimaryKey(Friend record);
    
    List<Friend> selectFriends(Friend friend);
}