package com.jy.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.jy.domain.Group;

@Repository
public interface GroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fgroup
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    int deleteByPrimaryKey(Integer gId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fgroup
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    int insert(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fgroup
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    int insertSelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fgroup
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    Group selectByPrimaryKey(Integer gId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fgroup
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    int updateByPrimaryKeySelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fgroup
     *
     * @mbggenerated Wed Aug 10 17:27:14 CST 2016
     */
    int updateByPrimaryKey(Group record);
    
    List<Group> selectGroups(Group group);
    
    List<Group> selectGroupsPage(@Param(value="group") Group group,
    		@Param(value="pageNum") int pageNum,@Param(value="pageSize") int pageSize);
    
    int selectGroupCount(Group group);
}